[package]
name = "boss-rush-2025-jam"
version = "0.1.0"
edition = "2021"

[dependencies]
bevy = "0.15.1"
enum-iterator = "2.1.0"

[features]
default = ["dev"]
dev = ["bevy/dynamic_linking", "bevy/bevy_dev_tools"]
web-dev = ["bevy/bevy_dev_tools"]
web = []
