[toolchain]
channel = "beta" # 1.84.0-beta.6
components = ["rustfmt", "rustc-dev", "rustc", "clippy", "rust-analyzer"]
targets = ["wasm32-unknown-unknown", "aarch64-apple-darwin"]
profile = "minimal"
