name: "Deploy to GitHub Pages"

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions-rust-lang/setup-rust-toolchain@v1
      - uses: Leafwing-Studios/cargo-cache@v2
      - run: command -v wasm-bindgen >/dev/null 2>&1 || cargo install wasm-bindgen-cli
      - run: sudo apt-get update; sudo apt-get install --no-install-recommends libasound2-dev libudev-dev libwayland-dev libxkbcommon-dev
      - name: Build
        run: RUSTFLAGS=--cfg=web_sys_unstable_apis cargo build --release --target wasm32-unknown-unknown --features web-dev
      - name: Wasm Bindgen
        run: wasm-bindgen --out-dir www/dist --target web ./target/wasm32-unknown-unknown/release/boss-rush-2025-jam.wasm
      - uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./www
